wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    huggingface_version: 3.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
adam_epsilon:
  desc: null
  value: 1.0e-08
best_model_dir:
  desc: null
  value: ../models/electra/best_model
cache_dir:
  desc: null
  value: cache_dir/
config:
  desc: null
  value: {}
custom_layer_parameters:
  desc: null
  value: []
custom_parameter_groups:
  desc: null
  value: []
dataloader_num_workers:
  desc: null
  value: 10
do_lower_case:
  desc: null
  value: false
doc_stride:
  desc: null
  value: 384
dynamic_quantize:
  desc: null
  value: false
early_stopping_consider_epochs:
  desc: null
  value: false
early_stopping_delta:
  desc: null
  value: 0
early_stopping_metric:
  desc: null
  value: correct
early_stopping_metric_minimize:
  desc: null
  value: false
early_stopping_patience:
  desc: null
  value: 3
encoding:
  desc: null
  value: null
eval_batch_size:
  desc: null
  value: 8
evaluate_during_training:
  desc: null
  value: false
evaluate_during_training_silent:
  desc: null
  value: true
evaluate_during_training_steps:
  desc: null
  value: 2000
evaluate_during_training_verbose:
  desc: null
  value: false
evaluate_each_epoch:
  desc: null
  value: true
fp16:
  desc: null
  value: true
gradient_accumulation_steps:
  desc: null
  value: 1
lazy_loading:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 4.0e-05
local_rank:
  desc: null
  value: -1
logging_steps:
  desc: null
  value: 50
manual_seed:
  desc: null
  value: null
max_answer_length:
  desc: null
  value: 100
max_grad_norm:
  desc: null
  value: 1.0
max_query_length:
  desc: null
  value: 64
max_seq_length:
  desc: null
  value: 128
model_class:
  desc: null
  value: QuestionAnsweringModel
model_name:
  desc: null
  value: deepset/electra-base-squad2
model_type:
  desc: null
  value: electra
multiprocessing_chunksize:
  desc: null
  value: 500
n_best_size:
  desc: null
  value: 20
n_gpu:
  desc: null
  value: 1
no_cache:
  desc: null
  value: false
no_save:
  desc: null
  value: false
null_score_diff_threshold:
  desc: null
  value: 0.0
num_train_epochs:
  desc: null
  value: 2
output_dir:
  desc: null
  value: ../models/electra
overwrite_output_dir:
  desc: null
  value: true
process_count:
  desc: null
  value: 10
quantized_model:
  desc: null
  value: false
reprocess_input_data:
  desc: null
  value: false
save_best_model:
  desc: null
  value: true
save_eval_checkpoints:
  desc: null
  value: true
save_model_every_epoch:
  desc: null
  value: true
save_optimizer_and_scheduler:
  desc: null
  value: true
save_steps:
  desc: null
  value: 2000
silent:
  desc: null
  value: false
skip_special_tokens:
  desc: null
  value: true
tensorboard_dir:
  desc: null
  value: null
thread_count:
  desc: null
  value: null
train_batch_size:
  desc: null
  value: 8
train_custom_parameters_only:
  desc: null
  value: false
use_cached_eval_features:
  desc: null
  value: true
use_early_stopping:
  desc: null
  value: false
use_multiprocessing:
  desc: null
  value: true
wandb_kwargs:
  desc: null
  value:
    name: deepset/electra-base-squad2
wandb_project:
  desc: null
  value: QuestionAnswering Model Comparison
warmup_ratio:
  desc: null
  value: 0.06
warmup_steps:
  desc: null
  value: 1967
weight_decay:
  desc: null
  value: 0
